### ISSUE TITLE
ImportError: cannot import name 'grpc_debug_server'

### ISSUE THREAD

**Issue by axelv** [tensorflow/tensorboard-plugin-example#10]
When running the second bazel command:
 `
bazel-bin/greeter_tensorboard/greeter_tensorboard '--logdir=/tmp/greeter_demo'
`
I get the following error:
```
INFO: Running command line: bazel-bin/greeter_tensorboard/greeter_tensorboard '--logdir=/tmp/greeter_demo'
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_root/d3e43e9fb8162b0d8a736168f9f53bee/execroot/io_github_tensorflow_tensorboard_plugin_example/bazel-out/darwin_x86_64-fastbuild/bin/greeter_tensorboard/greeter_tensorboard.runfiles/io_github_tensorflow_tensorboard_plugin_example/greeter_tensorboard/main.py", line 23, in <module>
    from tensorboard import main as tb_main
  File "/private/var/tmp/_bazel_root/d3e43e9fb8162b0d8a736168f9f53bee/execroot/io_github_tensorflow_tensorboard_plugin_example/bazel-out/darwin_x86_64-fastbuild/bin/greeter_tensorboard/greeter_tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/main.py", line 38, in <module>
    from tensorboard.plugins.debugger import debugger_plugin as debugger_plugin_lib
  File "/private/var/tmp/_bazel_root/d3e43e9fb8162b0d8a736168f9f53bee/execroot/io_github_tensorflow_tensorboard_plugin_example/bazel-out/darwin_x86_64-fastbuild/bin/greeter_tensorboard/greeter_tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/debugger/debugger_plugin.py", line 35, in <module>
    from tensorboard.plugins.debugger import debugger_server_lib
  File "/private/var/tmp/_bazel_root/d3e43e9fb8162b0d8a736168f9f53bee/execroot/io_github_tensorflow_tensorboard_plugin_example/bazel-out/darwin_x86_64-fastbuild/bin/greeter_tensorboard/greeter_tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/debugger/debugger_server_lib.py", line 33, in <module>
    from tensorflow.python.debug.lib import grpc_debug_server
ImportError: cannot import name 'grpc_debug_server'
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

I did a manual check and indeed in TensorFlow 1.3.0 the 'grpc_debug_server' doesn't exist.:
```
In [1]: from tensorflow.python.debug.lib import grpc_debug_server
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-33f414da0c97> in <module>()
----> 1 from tensorflow.python.debug.lib import grpc_debug_server

ImportError: cannot import name 'grpc_debug_server'

```

The modules exists in the master branch of TensorFlow so I suppose it is added only recently and there is a version problem in 'tensorboard-plugin-example'.

**Comment by chihuahua** [comment]
Hi @axelv, thank you for reporting. We were discussing this issue here. 
https://github.com/tensorflow/tensorboard/issues/431

Could you try installing TensorFlow nightly by `pip install`ing one of the links to a `whl` file listed under "Individual whl files" [here](https://github.com/tensorflow/tensorflow)?

Another way to install TensorFlow nightly (CPU support only, also Linux + Macs only) is via `pip install tf-nightly`. See the relevant [tf-nightly pypi package](https://pypi.python.org/pypi/tf-nightly).

https://github.com/tensorflow/tensorflow

**Comment by axelv** [comment]
Hi @chihuahua,

Currently I'm working with a built of the master branch and for now that seems to work.
Thanks anyway for the suggestions!

**Comment by chihuahua** [comment]
Ah yes! Working off of TF master works too.
