### ISSUE TITLE
type error out of the box

### ISSUE THREAD

**Issue by silky** [tensorflow/tensorboard-plugin-example#30]
when following the steps from the readme, after running the example i get:

```
E0521 15:46:04.173336 Thread-1 _internal.py:87] Error on request:
Traceback (most recent call last):
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_pocoo_werkzeug/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_pocoo_werkzeug/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/backend/application.py", line 271, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_pocoo_werkzeug/werkzeug/wrappers.py", line 291, in application
    return f(*args[:-2] + (request,))(*args[-2:])
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/plugins/core/core_plugin.py", line 136, in _serve_runs
    for run_name in run_names
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/plugins/core/core_plugin.py", line 136, in <dictcomp>
    for run_name in run_names
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/plugins/core/core_plugin.py", line 124, in get_first_event_timestamp
    return self._multiplexer.FirstEventTimestamp(run_name)
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 259, in FirstEventTimestamp
    return accumulator.FirstEventTimestamp()
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 235, in FirstEventTimestamp
    event = next(self._generator.Load())
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/backend/event_processing/directory_watcher.py", line 88, in Load
    for event in self._LoadInternal():
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/backend/event_processing/directory_watcher.py", line 112, in _LoadInternal
    for event in self._loader.Load():
  File "/home/noon/.cache/bazel/_bazel_noon/eb88fb0202132c299042995127b729f9/external/org_tensorflow_tensorboard/tensorboard/backend/event_processing/event_file_loader.py", line 53, in Load
    self._reader.GetNext(status)
TypeError: GetNext() takes 1 positional argument but 2 were given
```

i'm using the `tf-nightly` package for tensorflow, as recommended by the tensorboard repo itself:

```
> pip freeze
absl-py==0.2.1
astor==0.6.2
certifi==2016.2.28
gast==0.2.0
grpcio==1.12.0
Markdown==2.6.11
numpy==1.14.3
protobuf==3.5.2.post1
six==1.11.0
tb-nightly==1.9.0a20180520
termcolor==1.1.0
tf-nightly==1.9.0.dev20180520
Werkzeug==0.14.1
```

**Comment by nfelt** [comment]
This is fixed in TensorBoard 1.8.0, see tensorflow/tensorboard#1111, so we just need to update the WORKSPACE dep on TensorBoard to 1.8.0.

**Comment by johndpope** [comment]
I'm still seeing this. 
Using latest bazel + 1.8.0 

I force the install of tensorflow to 1.8.0 - but can't shake the workspace dependency.

![screen shot 2018-07-05 at 12 34 38 pm](https://user-images.githubusercontent.com/289994/42336084-885fc2a4-8050-11e8-9068-4667925ffb69.png)

tried this to no avail.

For some reason - it comes up with TensorBoard **1.6.0a0**. 
TensorBoard 1.6.0a0 at http://MAC-MBP161437.local:6006 (Press CTRL+C to quit)

```

http_archive(
    name = "org_tensorflow_tensorboard",
    sha256 = "a943c0242a07da4d445135ffc9a7c7cb987d9bd948ae733695bc16095dceec20",
    strip_prefix = "tensorboard-2fdb2199553729a6c5b42b7eb0305a101b454add",
    urls = ["https://github.com/tensorflow/tensorboard/archive/2fdb2199553729a6c5b42b7eb0305a101b454add.zip"],
)


```

**Comment by johndpope** [comment]
pip freeze 

absl-py==0.2.2
anaconda-client==1.6.3
appnope==0.1.0
argh==0.26.2
astor==0.6.2
-e git+https://github.com/openai/atari-py.git@9952b83bebc242608879710b49a81b193c339de9#egg=atari_py
autograd==1.1.10
backports.weakref==1.0rc1
backtrader==1.9.59.122
base58==0.2.5
beautifulsoup4==4.6.0
bleach==1.5.0
Box2D-kengz==2.3.3
bs4==0.0.1
cached-property==1.3.1
certifi==2017.4.17
chardet==3.0.4
ChatterBot==0.8.7
chatterbot-corpus==1.1.2
click==6.7
clyent==1.2.2
cycler==0.10.0
cymem==1.31.2
Cython==0.28.3
cytoolz==0.8.2
daiquiri==1.3.0
DateTime==4.2
decorator==4.0.11
dill==0.2.8.2
dlib==19.13.1
dm-sonnet==1.23
en-core-web-lg==2.0.0
en-core-web-sm==2.0.0
enso==0.1.6
entrypoints==0.2.2
enum34==1.1.6
et-xmlfile==1.0.1
evostra==1.0.1
-e git+https://github.com/IndicoDataSolutions/finetune.git@1b3d2f921ca65476cd26fc1b4193c4aa73d2d8fe#egg=finetune
ftfy==5.4.1
future==0.16.0
futures==3.1.1
gast==0.2.0
googlefinance==0.7
googlefinance.client==1.3.0
grpcio==1.12.1
gym==0.9.2
h5py==2.7.0
html5lib==0.9999999
idna==2.5
imageio==2.2.0
IndicoIo==1.1.5
int-date==0.1.8
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
jdcal==1.4
jedi==0.10.2
Jinja2==2.9.6
joblib==0.12.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
Keras==2.2.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.0.1
keras-rl==0.4.2
lucid==0.0.5
Mako==1.0.7
Markdown==2.6.9
MarkupSafe==0.23
mathparse==0.1.1
matplotlib==1.5.3
mido==1.2.8
mikasa==0.1
mikasa-gym==0.1
mistune==0.7.4
mock==2.0.0
msgpack==0.5.6
msgpack-numpy==0.4.1
msgpack-python==0.4.8
mujoco-py==0.5.7
murmurhash==0.28.0
natsort==5.0.3
nb-anacondacloud==1.4.0
nb-conda==2.2.0
nb-conda-kernels==2.1.0
nbconvert==5.2.1
nbformat==4.3.0
nbpresent==3.0.2
networkx==1.8.1
ninja==1.7.2.post2
nltk==3.2.4
nose==1.3.7
notebook==5.0.0
numexpr==2.6.5
numpy==1.14.5
oauthlib==2.0.2
olefile==0.44
opencv-python==3.4.1.15
openpyxl==2.5.4
pachi-py==0.0.21
pandas==0.23.1
pandas-datareader==0.5.0
pandocfilters==1.4.1
pathlib==1.0.1
patsy==0.4.1
pbr==3.0.1
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.2.1
Pint==0.8.1
plac==0.9.6
plotly==2.2.1
poloniex==0.4.6
preshed==1.0.0
profilehooks==1.10.0
prompt-toolkit==1.0.14
protobuf==3.4.0
ptyprocess==0.5.1
PyAlgoTrade==0.18
pybacktest==0.1.1
pydot==1.2.4
pygame==1.9.2a0
pyglet==1.2.4
Pygments==2.2.0
pygpu==0.6.9
pymongo==3.7.0
PyOpenGL==3.1.0
pyparsing==2.1.4
python-dateutil==2.6.0
python-magic==0.4.13
python-twitter==3.4.2
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.3.0
regex==2017.4.5
requests==2.18.1
requests-file==1.4.2
requests-ftp==0.3.1
requests-oauthlib==0.8.0
scikit-image==0.13.0
scikit-learn==0.18.1
scipy==0.19.1
seaborn==0.8.1
setuptools-git==1.2
simplegeneric==0.8.1
six==1.11.0
sklearn==0.0
sonnet==0.1.6
spacy==2.0.11
SQLAlchemy==1.2.8
statsmodels==0.8.0
stockstats==0.2.0
TA-Lib==0.4.17
tables==3.4.4
tensorboard==1.8.0
tensorflow==1.8.0
tensorflow-tensorboard==0.1.8
termcolor==1.1.0
terminado==0.6
testpath==0.3
Theano==0.9.0
thinc==6.10.2
toolz==0.9.0
torch==0.4.0
torchtext==0.2.3
tornado==4.5.1
tqdm==4.23.4
traitlets==4.3.2
tweepy==3.5.0
ujson==1.35
urllib3==1.21.1
wcwidth==0.1.7
webencodings==0.5
Werkzeug==0.12.2
wget==3.2
widgetsnbextension==2.0.0
word2vec==0.9.4
wrapt==1.10.11
wtte==0.0.2
zope.interface==4.4.3

**Comment by johndpope** [comment]
digging deeper - solved this by dropping in the source code for tensorboard-1.8.0 into directory.

then switching the line

_http_archive(
    name = "org_tensorflow_tensorboard",
    sha256 = "a943c0242a07da4d445135ffc9a7c7cb987d9bd948ae733695bc16095dceec20",
    strip_prefix = "tensorboard-2fdb2199553729a6c5b42b7eb0305a101b454add",
    urls = ["https://github.com/tensorflow/tensorboard/archive/1.9.0.zip"],
)_

to use the antipattern

**local_repository(
    name = "org_tensorflow_tensorboard",
    path = "tensorboard-1.8.0"
)**
