### ISSUE TITLE
Cannot buil greeter tensorboard

### ISSUE THREAD

**Issue by ArthurJrn** [tensorflow/tensorboard-plugin-example#37]
Hi, 

I have an issue with the building of the plugin example you explain in your README file. 
I have installed Bazel. Bazel version is '0.20.0', java -version '1.8.0_191'.

When I try to run 'bazel run //greeter_plugin:greeter_demo', I get the output 
'INFO: Invocation ID: 8601dacc-fed6-44e0-9a7b-60a128cc9f39
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 3.291s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @io_bazel_rules_closure; fetching'

So i tried to run with '--incompatible_remove_native_http_archive=false' as suggested, but then the secon command 'bazel run //greeter_tensorboard -- --logdir=/tmp/greeter_demo' failed again. I used the ''--incompatible_remove_native_http_archive=false' as suggested again, but build failed once again with ouput : 

'ERROR: /home/arthur/.cache/bazel/_bazel_arthur/e30b614ea0e301590f4fb76ff97dfe1d/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/compiler/BUILD:17:1: Building external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/compiler/libcompiler.jar (1 source file) and running annotation processors (ComponentProcessor) failed (Exit 1)
java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:114)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:106)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:109)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:117)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Generated
	at dagger.internal.codegen.SourceFileGenerator.<clinit>(SourceFileGenerator.java:43)
	at dagger.internal.codegen.ComponentProcessor.initSteps(ComponentProcessor.java:119)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.init(BasicAnnotationProcessor.java:119)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:675)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:774)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:869)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
	... 10 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more
Target //greeter_tensorboard:greeter_tensorboard failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 147.674s, Critical Path: 54.61s
INFO: 275 processes: 268 linux-sandbox, 7 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully'

This error seems to be related to #31 however the fix proposed didn't work for me. I am not familiar with Bazel, I would appreciate some help if someone has an idea!

Sincerely, 
Arthur Journe

'

**Comment by stephanwlee** [comment]
Hi @ArthurJrn, please downgrade to Bazel 0.19 for now.

Bazel 0.20 made some backwards incompatible change and their rules are not updated accordingly yet. Bugs to follow:
https://github.com/bazelbuild/rules_closure/issues/311
https://github.com/bazelbuild/rules_webtesting/issues/316
