### ISSUE TITLE
Bazel 0.23 problem

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorboard-plugin-example#47]
I get the below error. Ubuntu 1804, bazel 0.23
```
bazel run //greeter_plugin:greeter_demo
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: /home/tzaman/.cache/bazel/_bazel_tzaman/cf29eb9faa32ed21d3ea4adfbc42f13e/external/io_bazel_rules_closure/closure/stylesheets/closure_css_binary.bzl:90:17: Traceback (most recent call last):
	File "/home/tzaman/.cache/bazel/_bazel_tzaman/cf29eb9faa32ed21d3ea4adfbc42f13e/external/io_bazel_rules_closure/closure/stylesheets/closure_css_binary.bzl", line 81
		rule(implementation = _closure_css_bi..., <2 more arguments>)
	File "/home/tzaman/.cache/bazel/_bazel_tzaman/cf29eb9faa32ed21d3ea4adfbc42f13e/external/io_bazel_rules_closure/closure/stylesheets/closure_css_binary.bzl", line 90, in rule
		attr.label_list(cfg = "data", allow_files = True)
Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
ERROR: error loading package '': in /home/tzaman/.cache/bazel/_bazel_tzaman/cf29eb9faa32ed21d3ea4adfbc42f13e/external/io_bazel_rules_closure/closure/defs.bzl: Extension file 'closure/stylesheets/closure_css_binary.bzl' has errors
ERROR: error loading package '': in /home/tzaman/.cache/bazel/_bazel_tzaman/cf29eb9faa32ed21d3ea4adfbc42f13e/external/io_bazel_rules_closure/closure/defs.bzl: Extension file 'closure/stylesheets/closure_css_binary.bzl' has errors
INFO: Elapsed time: 7.420s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by mkenigs** [comment]
Agreed. Couldn't get it to build with latest version (0.24.1), but could after I downgraded
